services:

  nginx:
    image: nginx:1.26.2-alpine

    ports:
      - "8000:80"

    volumes:
      - "./static:/var/www/static"
      - "./media:/var/www/media"
      - "./nginx/default.conf:/etc/nginx/nginx.conf"

    depends_on:
      - backend-1

  database:
    image: postgres:17.2-alpine

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "127.0.0.1:5434:5432"
    volumes:

      - "./postgres_data:/var/lib/postgresql/data"
    env_file: .env

  cache:
    image: redis:7.4-alpine

  backend-1:
    build: .
    image: booking_ticket:0.2
    command: /bin/sh run.sh
    env_file: .env

    volumes:
      - "./static:/app/static"
      - "./media:/app/media"

    depends_on:
      - database
      - broker
      - cache

  celery-worker-1:
    image: booking_ticket:0.2
    build: .
    command: celery -A booking_ticket:celery_app worker -l INFO -n celery_worker_1
    env_file: .env

    depends_on:
      - database
      - cache
      - celery-backend
      - broker

  celery-backend:
    image: redis:7.4-alpine

  broker:
    image: rabbitmq:3-management

    ports:
      - "15672:15672"
      - "5672:5672"
    env_file: .env

    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"
