# Generated by Django 4.2.17 on 2025-01-10 11:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_booking_paid_remove_booking_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
