# Generated by Django 4.2.17 on 2025-01-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_passport_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='passport',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to=settings.AUTH_USER_MODEL),
        ),
    ]
