# Generated by Django 4.2.17 on 2025-01-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_passport_number_alter_passport_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
