# Generated by Django 4.2.17 on 2025-01-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_airport_airports_name_2bfdb6_idx_and_more'),
        ('app', '0006_remove_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.passport'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seat', to='trips.seat'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passport'], name='booking_passpor_1d0790_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_b99f68_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['seat'], name='booking_seat_id_bed325_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['first_name', 'last_name'], name='passports_first_n_ad47b2_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['owner'], name='passports_owner_i_771cd7_idx'),
        ),
    ]
