# Generated by Django 4.2.17 on 2025-01-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_booking_passport_alter_booking_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='app.payment'),
        ),
        migrations.AddField(
            model_name='passport',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
