# Generated by Django 4.2.17 on 2024-12-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-time_out'], 'verbose_name_plural': 'trips'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AlterField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='trips.company'),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.country'),
        ),
    ]
