# Generated by Django 4.2.17 on 2024-12-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_country_alter_company_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name_plural': 'trips'},
        ),
    ]
