# Generated by Django 4.2.17 on 2025-01-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('seat_configuration', models.JSONField(default=dict)),
                ('business_class_price', models.IntegerField(default=200)),
                ('economy_class_price', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'planes',
                'db_table': 'planes',
            },
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name_plural': 'seats'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='town_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='town_to',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(choices=[('business', 'Business'), ('economy', 'Economy')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.company'),
        ),
        migrations.AlterModelTable(
            name='seat',
            table='seats',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='trips.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='trips.city')),
            ],
            options={
                'verbose_name_plural': 'airports',
                'db_table': 'airports',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_trips', to='trips.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_trips', to='trips.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.plane'),
        ),
    ]
