# Generated by Django 4.2.17 on 2025-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_plane_alter_seat_options_remove_trip_airport_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['name'], name='airports_name_2bfdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='airports_city_id_572938_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='cities_name_a7bf2e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='cities_country_75dd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='companies_code_3c8feb_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='countries_name_19480f_idx'),
        ),
        migrations.AddIndex(
            model_name='plane',
            index=models.Index(fields=['model'], name='planes_model_9f2bea_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['trip'], name='seats_trip_id_f0cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_airport'], name='trips_departu_2a6473_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['arrival_airport'], name='trips_arrival_376b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['time_out'], name='trips_time_ou_375c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['plane'], name='trips_plane_i_19e3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company'], name='trips_company_264122_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['number'], name='trips_number_4207d6_idx'),
        ),
    ]
